---
- name: Install Terraform
  hosts: client
  tasks:
    - name: Download Terraform binary
      get_url:
        url: "https://releases.hashicorp.com/terraform/1.4.0/terraform_1.4.0_linux_amd64.zip"
        dest: "/tmp/terraform.zip"

    - name: Unzip Terraform binary
      unarchive:
        src: "/tmp/terraform.zip"
        dest: "/usr/local/bin"
        remote_src: yes

    - name: Ensure Terraform binary is executable
      file:
        path: "/usr/local/bin/terraform"
        mode: "0755"
